const PAY='https://nexgen999.github.io/PS5-Super-PLDMGR-Auto-Updater/json/payloads.json';
const PKG='https://nexgen999.github.io/PS5-Super-PLDMGR-Auto-Updater/PKGjson/pkg.json';let all=[],shown=[];
const $=x=>document.getElementById(x);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function base(){let ip=$('ip').value.trim(),p=parseInt($('port').value)||2120;if(!ip)throw Error('IP PS5 manquante');return `http://${ip}:${p}`}
function save(){localStorage.setItem('evoxps5ip',$('ip').value.trim());localStorage.setItem('evox5port',$('port').value||'2120');$('msg').textContent='Configuration enregistrée.'}
async function test(){save();try{let b=base();$('status').textContent='Test '+b+'…';let r=await fetch(b+'/api/status',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);$('dot').className='dot ok';$('status').textContent='🟢 ZHTTP disponible';$('msg').textContent='Serveur HTTP PS5 détecté : '+b}catch(e){$('dot').className='dot bad';$('status').textContent='🔴 Échec connexion';$('msg').textContent='Impossible de joindre le serveur : '+e.message}}
async function load(){try{let [a,b]=await Promise.all([fetch(PAY+'?t='+Date.now()).then(r=>r.json()),fetch(PKG+'?t='+Date.now()).then(r=>r.json())]);let pa=a.payloads||[],pk=b.payloads||b.pkgs||b.packages||[];all=[...pa.map(x=>({...x,_type:'payload'})),...pk.map(x=>({...x,_type:'pkg'}))];render()}catch(e){$('stats').textContent='Erreur : '+e.message}}
function render(){let q=$('q').value.toLowerCase(),t=$('type').value;shown=all.filter(x=>(t==='all'||x._type===t)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));$('stats').textContent=`${shown.length} élément(s) — ${shown.filter(x=>x._type==='payload').length} payload(s), ${shown.filter(x=>x._type==='pkg').length} PKG`;$('rows').innerHTML=shown.length?shown.map((x,i)=>row(x,i)).join(''):'<div class="empty">Aucun résultat.</div>';$('tiles').innerHTML=shown.length?shown.map((x,i)=>card(x,i)).join(''):'<div class="empty">Aucun résultat.</div>'}
function icon(x){return x._type==='pkg'?'📦':'🚀'}
function name(x){return x.name||x.title||x.filename||'Sans nom'}
function file(x){return x.filename||x.file||String(x.url||'').split('/').pop()}
function row(x,i){return `<div class="row"><div class="icon">${icon(x)}</div><div><div class="name">${esc(name(x))}</div><div class="desc">${esc(x.description||'')}</div></div><div><span class="tag">${esc(x.version||'latest')}</span></div><div><span class="tag">${esc(x.category||x.author||'—')}</span></div><div class="file">${esc(file(x))}</div><div class="actions"><button class="btn" onclick="download(${i})">⬇</button><button class="btn send" onclick="send(${i})">🚀 SEND</button></div></div>`}
function card(x,i){return `<article class="card"><div class="ct"><div class="icon">${icon(x)}</div><div><div class="name">${esc(name(x))}</div><div class="desc">${esc(x.description||'')}</div></div></div><div class="meta"><span class="tag">${esc(x.version||'latest')}</span><span class="tag">${esc(x.category||x.author||'—')}</span></div><div class="file">📄 ${esc(file(x))}</div><div class="actions"><button class="btn" onclick="download(${i})">⬇ Télécharger</button><button class="btn send" onclick="send(${i})">🚀 SEND</button></div></article>`}
async function download(i){let x=shown[i];if(!x?.url)return;let a=document.createElement('a');a.href=x.url;a.download=file(x);a.target='_blank';a.click()}
function modal(t,d){$('mt').textContent=t;$('md').textContent=d;$('log').textContent='';$('bar').style.width='0';$('modal').classList.add('open')}function log(s){$('log').textContent+=s+'\n'}function closeModal(){$('modal').classList.remove('open')}
async function send(i){let x=shown[i];try{let b=base();let dest=x._type==='pkg'?'/data/evox-store/pkg/':'/data/evox-store/payloads/';modal('🚀 SEND TO PS5',`${name(x)} → ${dest}`);log('Téléchargement depuis GitHub…');let r=await fetch(x.url);if(!r.ok)throw Error('Source HTTP '+r.status);let blob=await r.blob();$('bar').style.width='30%';log(`${(blob.size/1048576).toFixed(2)} MiB récupérés.`);let path=dest+file(x);log('Upload ZHTTP…');let u=await fetch(b+'/api/upload?path='+encodeURIComponent(path),{method:'POST',body:blob,headers:{'Content-Type':'application/octet-stream'}});if(!u.ok)throw Error('Upload HTTP '+u.status);$('bar').style.width='100%';log('✅ Transfert terminé.');$('dot').className='dot ok';$('status').textContent='🟢 Dernier transfert réussi'}catch(e){log('❌ '+e.message);$('dot').className='dot bad';$('status').textContent='🔴 Transfert échoué'}}
$('ip').value=localStorage.getItem('evoxps5ip')||'';$('port').value=localStorage.getItem('evox5port')||'2120';$('save').onclick=save;$('test').onclick=test;$('reload').onclick=load;$('q').oninput=render;$('type').onchange=render;load();
