name: Fetch Payloads from EvoX

on:
  schedule:
    - cron: '0 * * * *' # S'exécute toutes les heures
  workflow_dispatch: # Permet aussi de le lancer manuellement

jobs:
  update-payloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download payloads.json
        run: |
          mkdir -p json
          curl -L https://nexgen999.github.io/evoX-CoreOS/json/payloads.json -o json/payloads.json

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add json/payloads.json
          git diff --staged --quiet || git commit -m "Auto-update payloads.json from evoX-CoreOS"
          git push
